# Generated by Django 5.0 on 2025-11-08 14:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('STOP', 'Stop Order'), ('STOP_LIMIT', 'Stop-Limit Order')], default='MARKET', max_length=15)),
                ('entry_price', models.DecimalField(decimal_places=6, help_text='Actual fill price', max_digits=18)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=6, help_text='Limit price for limit orders', max_digits=18, null=True)),
                ('entry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_price', models.DecimalField(blank=True, decimal_places=6, help_text='Target price (informational)', max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, help_text='Stop loss price', max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, help_text='Take profit price', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='OPEN', max_length=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Simulated commission charged', max_digits=10)),
                ('slippage', models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Simulated slippage applied', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is REJECTED')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to='core.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'asset', 'status'], name='pt_user_asset_status_idx'), models.Index(fields=['asset', 'entry_at'], name='pt_asset_entry_idx'), models.Index(fields=['user', 'status', '-created_at'], name='pt_user_status_created_idx')],
            },
        ),
    ]
