# Generated by Django 5.0 on 2025-11-08 14:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper_trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirmPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('EVALUATION', 'Evaluation'), ('FUNDED', 'Funded')], default='EVALUATION', max_length=20)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, help_text='Maximum loss allowed in a single day', max_digits=12)),
                ('max_total_loss', models.DecimalField(decimal_places=2, help_text='Maximum total drawdown from starting balance', max_digits=12)),
                ('profit_target', models.DecimalField(blank=True, decimal_places=2, help_text='Profit needed to pass evaluation', max_digits=12, null=True)),
                ('min_trading_days', models.IntegerField(default=5, help_text='Minimum number of trading days required')),
                ('max_position_size', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum position size as percentage of balance', max_digits=5)),
                ('profit_split', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text="Trader's percentage of profits", max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starting_balance'],
            },
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=255)),
                ('masked_number', models.CharField(help_text='Masked card number, e.g. **** **** **** 4242', max_length=32)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('exp_month', models.CharField(blank=True, max_length=2)),
                ('exp_year', models.CharField(blank=True, max_length=4)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropFirmAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('alpaca_account_id', models.CharField(blank=True, max_length=100)),
                ('alpaca_account_status', models.CharField(blank=True, max_length=50)),
                ('alpaca_buying_power', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('PASSED', 'Passed Evaluation'), ('FAILED', 'Failed'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('stage', models.CharField(choices=[('EVALUATION', 'Evaluation'), ('FUNDED', 'Funded')], default='EVALUATION', max_length=20)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_water_mark', models.DecimalField(decimal_places=2, help_text='Highest balance reached', max_digits=12)),
                ('daily_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_winning_trades', models.IntegerField(default=0)),
                ('total_losing_trades', models.IntegerField(default=0)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trading_days', models.IntegerField(default=0)),
                ('last_trade_date', models.DateField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('is_simulation', models.BooleanField(default=True, help_text='True for simulated accounts (no real Alpaca integration)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_accounts', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prop_firm.propfirmplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_earned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_split', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(default='BANK_TRANSFER', max_length=50)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='prop_firm.propfirmaccount')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Account Created'), ('ACTIVATED', 'Account Activated'), ('TRADE_PLACED', 'Trade Placed'), ('TRADE_CLOSED', 'Trade Closed'), ('RULE_VIOLATION', 'Rule Violation'), ('BALANCE_UPDATE', 'Balance Updated'), ('STATUS_CHANGE', 'Status Changed'), ('PAYOUT_REQUEST', 'Payout Requested'), ('NOTE_ADDED', 'Note Added')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='prop_firm.propfirmaccount')),
            ],
            options={
                'verbose_name_plural': 'Account activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('DAILY_LOSS', 'Daily Loss Limit'), ('TOTAL_LOSS', 'Total Loss Limit'), ('POSITION_SIZE', 'Position Size Limit'), ('MIN_DAYS', 'Minimum Trading Days')], max_length=50)),
                ('description', models.TextField()),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='prop_firm.propfirmaccount')),
                ('related_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper_trading.papertrade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propfirmaccount',
            index=models.Index(fields=['user', 'status'], name='prop_firm_p_user_id_f06742_idx'),
        ),
        migrations.AddIndex(
            model_name='propfirmaccount',
            index=models.Index(fields=['account_number'], name='prop_firm_p_account_eec709_idx'),
        ),
        migrations.AddIndex(
            model_name='propfirmaccount',
            index=models.Index(fields=['status', 'stage'], name='prop_firm_p_status_549d57_idx'),
        ),
    ]
