# Generated by Django 5.0 on 2025-11-06 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop_firm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmaccount',
            name='gross_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='propfirmaccount',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='propfirmaccount',
            name='profit_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propfirmaccount',
            name='total_losing_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propfirmaccount',
            name='total_winning_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=255)),
                ('masked_number', models.CharField(help_text='Masked card number, e.g. **** **** **** 4242', max_length=32)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('exp_month', models.CharField(blank=True, max_length=2)),
                ('exp_year', models.CharField(blank=True, max_length=4)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
