# Generated by Django 5.0 on 2025-11-09 23:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop_firm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propfirmaccount',
            name='alpaca_account_id',
        ),
        migrations.RemoveField(
            model_name='propfirmaccount',
            name='alpaca_account_status',
        ),
        migrations.RemoveField(
            model_name='propfirmaccount',
            name='alpaca_buying_power',
        ),
        migrations.RemoveField(
            model_name='propfirmaccount',
            name='is_simulation',
        ),
        migrations.AddField(
            model_name='propfirmaccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propfirmaccount',
            name='high_water_mark',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propfirmplan',
            name='max_position_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='propfirmplan',
            name='min_trading_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='propfirmplan',
            name='profit_split',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5),
        ),
        migrations.DeleteModel(
            name='BillingDetail',
        ),
    ]
