# Generated by Django 5.0 on 2025-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop_firm', '0002_propfirmaccount_gross_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propfirmaccount',
            name='alpaca_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propfirmaccount',
            name='alpaca_account_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propfirmaccount',
            name='alpaca_buying_power',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
